### PR TITLE
Tab completion

### PR DESCRIPTION
**Pull request by adamrk**

### CODE REVIEW

**Comment by hellerve** [comment]
Looks good to me. Should I take over from here or do you want to keep working on it?

**Comment by adamrk** [comment]
Either is good for me. What do you think should happen next with it?

**Comment by hellerve** [comment]
I'm not sure, actually. The next thing I will be working on is reverse search.

Maybe tab completion should also complete keywords? I don't actually know whether that's a good idea and whether that should be context-dependent. What do you think?

**Comment by adamrk** [comment]
Yeah I think adding the keywords would be good. What's reverse search?

**Comment by hellerve** [comment]
It's incremental history search on the command line. Most readline implementations support that through `Ctrl+S`, and I thought it might be a good idea to add. It's now in the master branch and seems to work fairly well.

**Pull request merged**
